version: "3.3"
services:
  proxy:
    image: midasdesignlux.azurecr.io/lux_proxy
    container_name: proxy
    depends_on:
      - frontend
      - api
    restart: always
    ports:
      - "3001:80"
    networks:
      - bridge-net
  frontend:
    image: midasdesignlux.azurecr.io/lux_frontend
    container_name: frontend
    stdin_open: true
    depends_on:
      - api
    volumes:
      - /app/node_modules
    networks:
      - bridge-net
  api:
    image: midasdesignlux.azurecr.io/lux_api
    container_name: api
    restart: on-failure
    environment:
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOSTNAME: db
      DB_NAME: database_production
      NODE_ENV: production
    volumes:
      - /app/node_modules
    depends_on:
      - db
    networks:
      - bridge-net
db:
  image: mysql
  container_name: db
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: myPassword
    MYSQL_DATABASE: database_production
  healthcheck:
    test: '/usr/bin/mysql --user=root --password=myPassword --execute "SHOW DATABASES;"'
    interval: 30s
    timeout: 10s
    retries: 5
  networks:
    - bridge-net

networks:
  bridge-net:
    driver: bridge
