version: "3.3"
services:
  proxy:
    container_name: proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - api
    restart: always
    ports:
      - "3001:3001"
    networks:
      - bridge-net
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    depends_on:
      - api
    volumes:
      - /app/node_modules
    networks:
      - bridge-net
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOSTNAME: db
      DB_NAME: database_production
      NODE_ENV: production

    volumes:
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bridge-net
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myPassword
      MYSQL_DATABASE: database_production
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=myPassword --execute "SHOW DATABASES;"'
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3306:3306"
    networks:
      - bridge-net

networks:
  bridge-net:
    driver: bridge
